POST http://localhost:3003/api/users
content-type: application/json

{
	"username": "Yan", 
	"password": "009458"
}

POST http://localhost:3003/api/users
content-type: application/json

{
	"username": "Lin", 
	"password": "1234"
}