POST http://localhost:3003/api/users
content-type: application/json

{
	"username": "Karen", 
	"password": "1234"
}

POST http://localhost:3003/api/users
content-type: application/json

{
	"username": "Lin", 
	"password": "1234"
}

POST http://localhost:3003/api/users
content-type: application/json

{
	"username": "Demo", 
	"password": "Demo"
}

