POST http://localhost:3003/api/blogs
content-type: application/json

{
	"title": "fourth blog",
	"url": "localhost:3006",
	"author": "Yan",
	"likes": 98,
	"user": "5e468feecb53863f93335688"
}

POST http://localhost:3003/api/blogs
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkNoZW4iLCJpZCI6IjVlNGQwMTZiYjg1YzU1MjU4MGM2Njc4OSIsImlhdCI6MTU4MjEwNjU3OH0.2q3k7lV-cMgnXhOQeoJQ6zW8J5t7fXghU7F-gzbziKY

{
	"title": "New feature implemented!",
	"url": "localhost:3006",
	"author": "Lin",
	"likes": 68
	# "user": "5e4cfe3d946538226d041f0e"
}


