POST http://localhost:3003/api/blogs
content-type: application/json

{
	"title": "fourth blog",
	"url": "localhost:3006",
	"author": "Yan",
	"likes": 98,
	"user": "5e468feecb53863f93335688"
}

POST http://localhost:3003/api/blogs
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkxpbiIsImlkIjoiNWU0ZTUwOWQ3ZmM2YTE2YmM3YjkxY2RkIiwiaWF0IjoxNTgyMTkwNzU0fQ.7qppzw1DZqBNl-JV6vbrSYsVG-EkgBMW3tSGksjMWVA

{
	"title": "Today is Thursday!!",
	"url": "localhost:3006",
	"author": "Lin",
	"likes": 657
	# "user": "5e4cfe3d946538226d041f0e"
}


